### ISSUE TITLE
Question - The server's host key is not cached. You have no guarantee

### ISSUE THREAD

**Issue by CesarVerano** [Luis97lol/psftp-action#2]
First, thanks for create this action

My question is likely very basic, I am getting this error but I can't to found documentation about like set this in the pipeline

![image](https://github.com/Luis97lol/PSFTP/assets/107435617/11fa6735-fa9a-4ead-9b3f-727d539a9f9b)

Thanks for your help!

**Comment by Luis97lol** [comment]
Hi @CesarVerano , thanks to you for using the action.
In the documentation of the action in the Inputs section, there is a parameter called **hostkey**. 
![image](https://github.com/Luis97lol/PSFTP/assets/53903470/9a5948a6-82e5-4e9c-887b-32de16889af0)
You have to specify this action input parameter to fix the error.
At the end of the section there is an example showing how to use it.
![image](https://github.com/Luis97lol/PSFTP/assets/53903470/52599432-76a5-4c37-86d1-8c7ca29ae1d9)
DON'T FORGET TO USE AN ENVIRONMENT VARIABLE FOR IT !!!!
I hope it helps. If you have any problem, don't hesitate to comment it.
